### ISSUE TITLE
Can I map port internal port 80 to any other port?

### ISSUE THREAD

**Issue by beloso** [linuxserver/docker-letsencrypt-armhf#52]
I am using this docker image to update my certificates.

I have another container (for pi-hole) that requires external port 80 for proper functioning.

I can't overlap both, so is it okay If I just map letencrypt port 80 to let's say, 8081?

**Comment by sparklyballs** [comment]
map the port on the LE image like so 

`-p 8081:80` then forward port 80 to port 8081 and the ip of the docker host on your router

**Comment by beloso** [comment]
Thank you
