### ISSUE TITLE
Request time out // Can't reach the page

### ISSUE THREAD

**Issue by aidlsantoso76** [linuxserver/docker-letsencrypt-armhf#80]
Hai, I think i follow the instruction and nothing error but i can't reach my page.

my container log is "Server ready"
this is my config
docker create \
  --cap-add=NET_ADMIN \
  --name=letsencrypt \
  -v /home/user/docker-nginx-letsencrypt:/config \
  -e PGID=1000 -e PUID=1000  \
  -e EMAIL=mail@gmail.com \
  -e URL=mydomain.duckdns.org \
  -e SUBDOMAINS=hass,portainer \
  -e VALIDATION=duckdns \
  -e DUCKDNSTOKEN=6401de96-XXXX-XXXX-XXXX-fef42fd8ed57 \
  -e TZ=Asia/Jakarta \
  lsioarmhf/letsencrypt

anyone know what's happen?﻿ Thank you

**Comment by aptalca** [comment]
Are you trying to go to the https address?

**Comment by aptalca** [comment]
Yes. How do you expect the request to end up at the container?

You also need to map port 443 in the docker create. 

Please read the readme. It explains it all, with examples
